### ISSUE TITLE
Long press opens context menu in Chrome instead of initiating drag and drop

### ISSUE THREAD

**Issue by porst17** [polymake/matchthenet#1]
I tested on Ubuntu 18.04 with Chrome 69. If I long press (with a mouse or touch screen) on one of the flattened nets at the bottom, the context menu appears. On Firefox, it initiates drag and drop.

There seems no way to disable the long-press -for-context-menu feature in Chrome itself, but there is a workaround that disables the context menu altogether:
```
window.oncontextmenu = function(event) { return false; }
```

This worked for me.

**Comment by benlorenz** [comment]
Thanks for the report, should be fixed now.
